name: Deploy Client to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish WASM
        run: dotnet publish src/PortfolioClient/ -c Release -o build

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/wwwroot

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/deploy-pages@v4
        with:
          spa-fallback: true
